# Generated by Django 3.1.7 on 2022-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
