# Generated by Django 3.1.7 on 2022-08-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_talent',
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_artist_talented',
            field=models.BooleanField(default=False),
        ),
    ]
