# Generated by Django 3.1.7 on 2022-08-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20220807_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=350)),
            ],
            options={
                'verbose_name': 'voucher',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.collection'),
        ),
    ]
