# Generated by Django 3.1.7 on 2022-08-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20220807_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'collection'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.collection'),
        ),
    ]
