# Generated by Django 3.1.7 on 2022-08-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_remove_artwork_isprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, default='/defaultImage.png', null=True, upload_to=''),
        ),
    ]
