# Generated by Django 3.2.20 on 2023-09-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0007_auto_20230829_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='favorite_artworks',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
