# Generated by Django 3.2.20 on 2023-09-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20230913_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
    ]
