# Generated by Django 3.2.20 on 2023-09-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('artworks', '0009_auto_20230913_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='cities_light.City',
            ),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='cities_light.Country',
            ),
        ),
    ]
