# Generated by Django 3.2.20 on 2023-10-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20230913_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='contract',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='artist',
            name='vadee_fee',
            field=models.IntegerField(default=10),
        ),
    ]
