# Generated by Django 3.2.20 on 2023-10-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auto_20231005_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='royalty_fee',
            field=models.IntegerField(default=10),
        ),
    ]
