# Generated by Django 3.2.20 on 2023-10-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_artist_royalty_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='edition_number',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='token_Uri',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='artwork_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='edition',
            field=models.IntegerField(default='', max_length=350),
        ),
    ]
