# Generated by Django 3.2.20 on 2023-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_auto_20231005_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='price_dollar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='price_wei',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='signature',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
