# Generated by Django 3.2.20 on 2023-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_auto_20231005_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
