# Generated by Django 3.2.20 on 2023-10-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_voucher_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='voucher',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='artwork_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
    ]
