# Generated by Django 3.1.7 on 2022-06-24 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0018_auto_20220623_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='favorites',
        ),
        migrations.AddField(
            model_name='artwork',
            name='favorite_artworks',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_favorite_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
