# Generated by Django 3.1.7 on 2022-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0019_auto_20220624_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_notable',
            field=models.BooleanField(default=False),
        ),
    ]
