# Generated by Django 3.2.20 on 2023-10-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0021_auto_20231027_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technique_artworks', to='artworks.theme'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_artworks', to='artworks.genre'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='them_artworks', to='artworks.theme'),
        ),
    ]
