# Generated by Django 3.2.20 on 2023-10-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0022_auto_20231027_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='technique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technique_artworks', to='artworks.technique'),
        ),
    ]
