# Generated by Django 3.1.7 on 2022-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0022_origin_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
