# Generated by Django 3.1.7 on 2022-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0023_auto_20220715_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
