# Generated by Django 3.2.20 on 2023-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0023_alter_artwork_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followed_artists',
            field=models.ManyToManyField(to='artworks.Artist'),
        ),
    ]
