# Generated by Django 3.2.20 on 2023-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0024_myuser_followed_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='followed_artists',
            field=models.ManyToManyField(related_name='followers', to='artworks.Artist'),
        ),
    ]
