# Generated by Django 3.2.20 on 2023-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0025_auto_20231102_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='similar_artists',
            field=models.ManyToManyField(to='artworks.Artist'),
        ),
    ]
