# Generated by Django 3.2.20 on 2023-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0026_artist_similar_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='similar_artworks',
            field=models.ManyToManyField(to='artworks.Artwork'),
        ),
    ]
