# Generated by Django 3.1.7 on 2022-07-28 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0026_auto_20220715_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artwork_artist', to='artworks.artist'),
        ),
    ]
