# Generated by Django 3.2.20 on 2023-11-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0028_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-created_at',), 'verbose_name': 'genre', 'verbose_name_plural': 'genre'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='similar_artists',
            field=models.ManyToManyField(related_name='_artworks_artist_similar_artists_+', to='artworks.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='similar_artworks',
            field=models.ManyToManyField(related_name='_artworks_artwork_similar_artworks_+', to='artworks.Artwork'),
        ),
    ]
