# Generated by Django 3.2.20 on 2023-11-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0030_myuser_saved_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='similar_artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='_artworks_artist_similar_artists_+', to='artworks.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='similar_artworks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_artworks_artwork_similar_artworks_+', to='artworks.Artwork'),
        ),
    ]
