# Generated by Django 3.2.24 on 2024-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0032_auto_20240211_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_ipfs_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
