# Generated by Django 3.2.24 on 2024-02-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0033_artwork_image_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='metadata_ipfs_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
