version: "3.8"

services:
  backend:
    image: ${CONTAINER_IMAGE:-backend}
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile.prod
    # command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    # env_file:
    #   - ./.env

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  media:
    image: flashspys/nginx-static
    volumes:
      - media_volume:/static

  static:
    image: flashspys/nginx-static
    expose:
      - 80
    volumes:
      - static_volume:/static

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   ports:
  #     - 1818:80
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
