# Generated by Django 3.2.20 on 2023-08-28 17:14

from django.db import migrations


def create_cart(apps, schema_editor):
    User = apps.get_model("artworks", "MyUser")
    Cart = apps.get_model("cart", "Cart")
    for user in User.objects.all():
        Cart.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_cart, migrations.RunPython.noop)]
